### ISSUE TITLE
Spelling mistake in 00_basics README.md

### ISSUE THREAD

**Issue by PetterRosander** [tdep-developers/tdep-tutorials#31]
Under the title "Extracting forceconstants".

The command:
`extract_forceconstant -rc2 100 -s 50 > fc2.log`
Should be:
`extract_forceconstants -rc2 100 -s 50 > fc2.log`

**Comment by PetterRosander** [comment]
In the same file (at least for me)

the --persist option to gnuplot should be after the filename, i.e.,

gnuplot --persist outfile.dispersion_relations.gnuplot

should be:

gnuplot outfile.dispersion_relations.gnuplot --persist

**Comment by flokno** [comment]
seems to be fixed
