### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sponce24** [tdep-developers/tdep-tutorials#39]
https://github.com/tdep-developers/tdep-tutorials/blame/4066eecc8abbee11b4eb9d8beb7c42198090595b/01_sampling/example_materials/MgO/README.md#L68

Might be` -T 300 ` instead ? 

You may want to add `phonon_dispersion_relations --dos` to the Makefile to be able to plot the convergence DOS at the end.

**Comment by flokno** [comment]
thanks!
