### ISSUE TITLE
-rc3 flag is missing

### ISSUE THREAD

**Issue by pzeiger** [tdep-developers/tdep-tutorials#51]
https://github.com/tdep-developers/tdep-tutorials/blob/5cb55c44c622c32e7f6e638fd9b3ed75fec7a6e9/07_Raman/example_GaN/sampling.300K/iter.000/Makefile#L11

**Comment by flokno** [comment]
hmm I think it doesn't really make sense to do this all the way up in the self-consistent loop. Should be looked at once the 2nd order is converged
